#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata":{"name":"harbor-ingress"}, "kind": "Ingress"})
---
kind: Ingress
metadata:
  annotations:
    #@overlay/match missing_ok=True
    projectcontour.io/response-timeout: "900s"
spec:
  tls:
  #@overlay/match by=overlay.subset({"secretName": "harbor-tls"})
  - secretName: contour-tls-delegation-cert
