#@ load("/values.star", "values")
#@ load("@ytt:base64", "base64")
---
#@ if values.dex.config.connector == "oidc" :
apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: #@ values.dex.namespace
type: Opaque
data:
  clientId: #@ base64.encode("{}".format(values.dex.config.oidc.CLIENT_ID))
  clientSecret: #@ base64.encode("{}".format(values.dex.config.oidc.CLIENT_SECRET))
#@ end