apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-system-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-extension-sa
  namespace: tanzu-system-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-extension-role
  namespace: tanzu-system-monitoring
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-extension-rolebinding
  namespace: tanzu-system-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-extension-role
subjects:
- kind: ServiceAccount
  name: grafana-extension-sa
  namespace: tanzu-system-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-extension-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-extension-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-extension-cluster-role
subjects:
- kind: ServiceAccount
  name: grafana-extension-sa
  namespace: tanzu-system-monitoring
