#@ load("@ytt:data", "data")
---
#@ if data.values.gcp != None:
apiVersion: v1
data: {
  "gcp.key.json": #@ data.values.gcp.key
}
kind: Secret
metadata:
  name: gcp-credentials-secret
  namespace: tanzu-system-service-discovery
#@ end