#@data/values
---
vsphere:
  cluster_name: tanzu-advanced-cluster
  supervisor_namespace: tanzu-advanced
  storage_policy_name: pacific-gold-storage-policy
ingress:
  domain: demo.example.com
  contour_tls_namespace: tanzu-system-ingress
  contour_tls_secret: contour-tls-delegation-cert
acme:
  email: user@example.com
aws: # Remove nested properties if you are not using Route53 to manage the domain / for external DNS
  region: us-east-1
  credentials:
    accessKey: ACCESS
    secretKey: SECRET
gcp: # Remove nested properties if you are not using GCP to manage the domain / for external DNS
  project: project-name
  key: # Base64 encoded gcp.key.json file content
harbor:
  adminPassword: 
  diskSize: 50Gi
