#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: tanzu-system-service-discovery
data: {
  "aws_access_key_id": #@ base64.encode(data.values.aws.credentials.accessKey)
  , "aws_secret_access_key": #@ base64.encode(data.values.aws.credentials.secretKey)
}
