#@ load("@ytt:data", "data")
---

# Namespace in which to deploy ExternalDNS.
namespace: tanzu-system-service-discovery

# Deployment-related configuration.
deployment:
 args:
   - --source=service
   - --source=ingress
   - --source=contour-httpproxy # Provide this to enable Contour HTTPProxy support. Must have Contour installed or ExternalDNS will fail.
   - #@ "--aws-assume-role=" + str(data.values.aws.externalDnsRoleArn)
   - #@ "--domain-filter=" + str(data.values.ingress.domain)
   - --policy=upsert-only
   - --registry=txt
   - #@ "--txt-owner-id=" + str(data.values.aws.zoneId)  
   - --txt-prefix=txt # Disambiguates TXT records from CNAME records.
   - --provider=aws
   - --aws-zone-type=public # Looks only at public hosted zones. Valid values are public, private, or no value for both.
   - --aws-prefer-cname
 env:
   - name: AWS_ACCESS_KEY_ID
     valueFrom:
       secretKeyRef:
         name: route53-credentials
         key: aws_access_key_id
   - name: AWS_SECRET_ACCESS_KEY
     valueFrom:
       secretKeyRef:
         name: route53-credentials
         key: aws_secret_access_key
 securityContext: {}
 volumeMounts: []
 volumes: []
