---
apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-system-registry
  labels:
    app: "harbor"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tanzu-system-registry
  name: harbor
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: tanzu-system-registry
  name: harbor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harbor
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tanzu-system-registry