#@ load("/values.star", "values")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: gangway
  namespace: #@ values.gangway.namespace
type: Opaque
data:
  sessionKey: #@ base64.encode("{}".format(values.gangway.secret.sessionKey))
  clientSecret: #@ base64.encode("{}".format(values.gangway.secret.clientSecret))