#@data/values
#@overlay/match-child-defaults missing_ok=True

---
contour:
  namespace: tanzu-system-ingress
  config:
    server:
      xdsServerType: null
    tls:
      minimumProtocolVersion: null
      fallbackCertificate:
        name: null
        namespace: null
      envoyClientCertificate:
        name: null
        namespace: null
    leaderelection:
      configmapName: leader-elect
      configmapNamespace: tanzu-system-ingress
    disablePermitInsecure: false
    accesslogFormat: envoy
    jsonFields: null
    useProxyProtocol: false
    defaultHTTPVersions: null
    timeouts:
      requestTimeout: null
      connectionIdleTimeout: null
      streamIdleTimeout: null
      maxConnectionDuration: null
      connectionShutdownGracePeriod: null
    cluster:
      dnsLookupFamily: null
    debug: false
    ingressStatusAddress: null
  certificate:
    duration: 8760h
    renewBefore: 360h
  deployment:
    replicas: 2
  image:
    repository: "projects.registry.vmware.com/tkg"
    name: contour
    tag: v1.12.0_vmware.1
    pullPolicy: "IfNotPresent"
envoy:
  image:
    repository: "projects.registry.vmware.com/tkg"
    name: envoy
    tag: v1.17.0_vmware.1
    pullPolicy: "IfNotPresent"
  hostPort:
    enable: true
    http: 80
    https: 443
  service:
    type: null
    externalTrafficPolicy: Cluster
    nodePort:
      http: null
      https: null
    aws:
      LBType: classic
    disableWait: false
    annotations: {}
  deployment:
    hostNetwork: false
    terminationGracePeriodSeconds: 300
  loglevel: info
