#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infrastructure_provider: "aws"
contour:
  image:
    repository: projects.registry.vmware.com/tkg
  config:
    #@overlay/replace
    defaultHTTPVersions: 
    - "HTTP/1.1"
envoy:
  image:
    repository: projects.registry.vmware.com/tkg
