#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.all
#@overlay/match-child-defaults missing_ok=True
---
CLUSTER_NAME: #@ data.values.tkg.management_cluster.name
CLUSTER_PLAN: dev
TMC_REGISTRATION_URL: #@ data.values.tmc.registration_url
VSPHERE_CONTROL_PLANE_ENDPOINT: #@ data.values.tkg.management_cluster.controlplane.endpoint
VSPHERE_WORKER_DISK_GIB: #@ data.values.tkg.management_cluster.worker.disk
VSPHERE_WORKER_NUM_CPUS: #@ data.values.tkg.management_cluster.worker.cpu
VSPHERE_WORKER_MEM_MIB: #@ data.values.tkg.management_cluster.worker.memory
VSPHERE_CONTROL_PLANE_DISK_GIB: #@ data.values.tkg.management_cluster.controlplane.disk
VSPHERE_CONTROL_PLANE_NUM_CPUS: #@ data.values.tkg.management_cluster.controlplane.cpu
VSPHERE_CONTROL_PLANE_MEM_MIB: #@ data.values.tkg.management_cluster.controlplane.memory
AVI_ENABLE: true
AVI_DISABLE_INGRESS_CLASS: true
AVI_CONTROLLER: #@ data.values.avi.controller_ip
AVI_USERNAME: "admin"
AVI_PASSWORD: #@ data.values.avi.password
AVI_CLOUD_NAME: "Default-Cloud"
AVI_SERVICE_ENGINE_GROUP: "Default-Group"
AVI_DATA_NETWORK: #@ data.values.avi.network
AVI_DATA_NETWORK_CIDR: #@ data.values.avi.network_cdir 
AVI_CA_DATA_B64: #@ data.values.avi.ca_data_b64 
