#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ data.values.ingress.contour_tls_secret
  namespace: #@ data.values.ingress.contour_tls_namespace
spec:
  commonName: #@ "*.{}".format(data.values.ingress.domain)
  dnsNames:
  - #@ "*.{}".format(data.values.ingress.domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  keySize: 2048
  organization:
  - vmware
  renewBefore: 360h0m0s
  secretName: #@ data.values.ingress.contour_tls_secret
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "eduk8s,tanzu-system-registry,concourse,kubeapps"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
