#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ "cnr-{}".format(data.values.ingress.contour_tls_secret)
  namespace: #@ data.values.ingress.contour_tls_namespace
spec:
  commonName: #@ "*.cnr.{}".format(data.values.ingress.domain)
  dnsNames:
  - #@ "*.cnr.{}".format(data.values.ingress.domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  keySize: 2048
  organization:
  - vmware
  renewBefore: 360h0m0s
  secretName: #@ "cnr-{}".format(data.values.ingress.contour_tls_secret)
