#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")
#@ load("globals.star", "get_kapp_annotations")

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ values.externalDns.namespace
  #@ annotations = get_kapp_annotations("Namespace")
  #@ if annotations:
  #@overlay/match missing_ok=True
  annotations: #@ annotations
  #@ end
