#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata":{"name":"harbor-ingress"}, "kind": "Ingress"})
---
kind: Ingress
spec:
  tls:
  #@overlay/match by=overlay.subset({"secretName": "harbor-tls"})
  - secretName: tanzu-system-ingress/contour-tls-delegation-cert