#@ load("values.star", "values")
#@ if values.monitoring.ingress.enabled:
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prometheus-httpproxy
  namespace: #@ values.monitoring.namespace
  labels:
    app: prometheus
spec:
  virtualhost:
    fqdn: #@ values.monitoring.ingress.virtual_host_fqdn
    tls:
      secretName: prometheus-tls
  routes:
    - conditions:
      - prefix: #@ values.monitoring.ingress.prometheus_prefix
      pathRewritePolicy:
        replacePrefix:
          - prefix: #@ values.monitoring.ingress.prometheus_prefix
            replacement: /
      services:
        - name: prometheus-server
          port: 80
    - conditions:
      - prefix: #@ values.monitoring.ingress.alertmanager_prefix
      pathRewritePolicy:
        replacePrefix:
        - prefix: #@ values.monitoring.ingress.alertmanager_prefix
          replacement: /
      services:
        - name: prometheus-alertmanager
          port: 80
#@ end