#@ load("@ytt:data", "data")
imageTag: 7.4.0
concourse:
  web:
    externalUrl: #@ "https://concourse.{}".format(data.values.ingress.domain)
    auth:
      mainTeam:
        localUser: #@ data.values.concourse.username
web:
  ingress:
    enabled: true
    hosts: #@ ["concourse.{}".format(data.values.ingress.domain)]
    tls:
    - secretName: #@ data.values.ingress.contour_tls_secret
      hosts: #@ ["concourse.{}".format(data.values.ingress.domain)]
secrets:
  localUsers: #@ "{}:{}".format(data.values.concourse.username,data.values.concourse.password)
#@ if hasattr(data.values.concourse, "requiredNodeType"):
worker:
  nodeSelector:
    type: concourse
  tolerations:
  - effect: PreferNoSchedule
    key: type
    operator: Equal
    value: concourse
#@ end
persistence:
  worker:
    storageClass: concourse-workers
