#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
#@ if data.values.gcp != None:
data: {
  "gcp.key.json": #@ data.values.gcp.key
}
kind: Secret
metadata:
  name: gcp-credentials-secret
  namespace: tanzu-system-service-discovery
#@ end
#@ if data.values.aws != None:
data: {
  "aws_access_key_id": #@ base64.encode(data.values.aws.credentials.accessKey)
  , "aws_secret_access_key": #@ base64.encode(data.values.aws.credentials.secretKey)
}
kind: Secret
metadata:
  name: route53-credentials
  namespace: tanzu-system-service-discovery
#@ end
