---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: default
  labels:
    app.kubernetes.io/name: grafana
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "MElzUU55SjQ2UUp2QW05RzJicmFjU3hKQlhBYXZ5WFZVb20xbllsWA=="
  ldap-toml: ""
