#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")

#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata": {"name": "grafana"}})
---
data:
  grafana.ini: #@ values.monitoring.grafana.config.grafana_ini
