#@ load("/values.star", "values")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name": "grafana"}})
---
type: #@ values.monitoring.grafana.secret.type 
data:
  admin-user: #@ values.monitoring.grafana.secret.admin_user
  admin-password: #@ values.monitoring.grafana.secret.admin_password
  ldap-toml: #@ values.monitoring.grafana.secret.ldap_toml
