---
# Source: cadvisor/deploy/kubernetes/base/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: cadvisor
    app: prometheus
  name: prometheus-cadvisor
  namespace: cadvisor
